export type RuntimeProfile = "local" | "ci" | "staging";
type Environment = Record<string, string | undefined>;
export type ServerEnvironment = Readonly<{ profile: RuntimeProfile; port: number; databaseUrl: URL; objectStorage: Readonly<{ endpoint: URL; region: string; accessKeyId: string; secretAccessKey: string; buckets: Readonly<{ quarantine: string; clean: string; derived: string }> }>; oidc: Readonly<{ issuer: URL; jwksUri: URL; audience: string; organizationClaim: string }>; allowedWebOrigins: readonly URL[]; deploymentId: string; releaseVersion: string; syntheticDataOnly: true }>;
const REQUIRED = ["EVIDENCE_LOOP_ENV","PORT","SYNTHETIC_DATA_ONLY","DATABASE_URL","S3_ENDPOINT","S3_REGION","S3_ACCESS_KEY_ID","S3_SECRET_ACCESS_KEY","S3_BUCKET_QUARANTINE","S3_BUCKET_CLEAN","S3_BUCKET_DERIVED","OIDC_ISSUER","OIDC_JWKS_URI","OIDC_AUDIENCE","OIDC_ORGANIZATION_CLAIM","ALLOWED_WEB_ORIGINS","DEPLOYMENT_ID","RELEASE_VERSION"] as const;
const BUCKET=/^[a-z0-9][a-z0-9.-]{1,61}[a-z0-9]$/; const CLAIM=/^[A-Za-z][A-Za-z0-9_.:/-]{0,127}$/;
export class EnvironmentError extends Error { readonly variable:string; readonly code:string; constructor(variable:string,code:string){super(`${variable}: ${code}`);this.variable=variable;this.code=code} }
function value(s:Environment,k:string){const v=s[k]?.trim();if(!v)throw new EnvironmentError(k,"required");return v}
function url(s:Environment,k:string){try{return new URL(value(s,k))}catch{throw new EnvironmentError(k,"invalid-url")}}
function loopback(v:URL){
  if (["localhost","::1","[::1]","0:0:0:0:0:0:0:1"].includes(v.hostname)) return true;
  if (/^127\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$/.test(v.hostname)) {
    const octets = v.hostname.split(".").map(Number);
    return octets[0] === 127 && octets.every(o => o >= 0 && o <= 255);
  }
  if (/^::ffff:127\./.test(v.hostname)) return true;
  return false;
}
function http(v:URL){return v.protocol==="http:"||v.protocol==="https:"}
function profile(s:Environment):RuntimeProfile {const v=value(s,"EVIDENCE_LOOP_ENV");if(v==="local"||v==="ci"||v==="staging")return v;throw new EnvironmentError("EVIDENCE_LOOP_ENV","unsupported-profile")}
function origins(s:Environment,p:RuntimeProfile){const all=value(s,"ALLOWED_WEB_ORIGINS").split(",").map(x=>{try{return new URL(x.trim())}catch{throw new EnvironmentError("ALLOWED_WEB_ORIGINS","invalid-url")}});if(!all.length||all.some(x=>!http(x)||(p==="staging"&&(x.protocol!=="https:"||loopback(x)))))throw new EnvironmentError("ALLOWED_WEB_ORIGINS","invalid-origin");return Object.freeze(all)}
export function parseServerEnvironment(s:Environment=process.env):ServerEnvironment {for(const k of Object.keys(s))if(/^(NEXT_PUBLIC_|VITE_|PUBLIC_)/.test(k))throw new EnvironmentError(k,"browser-namespace-not-allowed");if(s.OIDC_CLIENT_SECRET?.trim()||s.OIDC_CLIENT_ID?.trim())throw new EnvironmentError("OIDC_CLIENT_SECRET","resource-server-does-not-use-client-credentials");for(const k of REQUIRED)value(s,k);const p=profile(s), db=url(s,"DATABASE_URL"), store=url(s,"S3_ENDPOINT"), issuer=url(s,"OIDC_ISSUER"), jwks=url(s,"OIDC_JWKS_URI");if(!/^postgres(?:ql)?:$/.test(db.protocol))throw new EnvironmentError("DATABASE_URL","invalid-protocol");if(!http(store)||!http(issuer)||!http(jwks))throw new EnvironmentError("OIDC_ISSUER","invalid-protocol");if(!CLAIM.test(value(s,"OIDC_ORGANIZATION_CLAIM")))throw new EnvironmentError("OIDC_ORGANIZATION_CLAIM","invalid-claim-name");if(value(s,"SYNTHETIC_DATA_ONLY")!=="true")throw new EnvironmentError("SYNTHETIC_DATA_ONLY","must-be-true-for-a01");if(p==="staging"&&([db,store,issuer,jwks].some(loopback)||[store,issuer,jwks].some(x=>x.protocol!=="https:")))throw new EnvironmentError("OIDC_ISSUER","staging-requires-https-non-loopback");if(p==="staging"&&[value(s,"S3_ACCESS_KEY_ID"),value(s,"S3_SECRET_ACCESS_KEY")].some(x=>x.length<16||/^(change-me|example|placeholder)$/i.test(x)))throw new EnvironmentError("S3_ACCESS_KEY_ID","staging-placeholder-credential");const b={quarantine:value(s,"S3_BUCKET_QUARANTINE"),clean:value(s,"S3_BUCKET_CLEAN"),derived:value(s,"S3_BUCKET_DERIVED")};if(Object.values(b).some(x=>!BUCKET.test(x))||new Set(Object.values(b)).size!==3)throw new EnvironmentError("S3_BUCKET_QUARANTINE","invalid-or-duplicate-bucket");const port=Number(value(s,"PORT"));if(!Number.isInteger(port)||port<1||port>65535)throw new EnvironmentError("PORT","invalid-port");return Object.freeze({profile:p,port,databaseUrl:db,objectStorage:Object.freeze({endpoint:store,region:value(s,"S3_REGION"),accessKeyId:value(s,"S3_ACCESS_KEY_ID"),secretAccessKey:value(s,"S3_SECRET_ACCESS_KEY"),buckets:Object.freeze(b)}),oidc:Object.freeze({issuer,jwksUri:jwks,audience:value(s,"OIDC_AUDIENCE"),organizationClaim:value(s,"OIDC_ORGANIZATION_CLAIM")}),allowedWebOrigins:origins(s,p),deploymentId:value(s,"DEPLOYMENT_ID"),releaseVersion:value(s,"RELEASE_VERSION"),syntheticDataOnly:true})}
export function redactEnvironmentError(e:unknown){return e instanceof EnvironmentError?`${e.variable}: ${e.code}`:"environment: invalid"}
